[book]
authors = ["NYU ProcDesign Team"]
language = "en"
src = "src"
title = "NYU Processor Design Documentation"

[output.html]
default-theme = "ayu"
smart-punctuation = true
git-repository-url = "https://github.com/NYU-Processor-Design/nyu-processor-design.github.io/tree/main"
edit-url-template = "https://github.com/NYU-Processor-Design/nyu-processor-design.github.io/tree/main/{path}"

[output.html.fold]
enable = true
level = 0
